### ISSUE TITLE
Ghost users staying in the rooms (Jitsi-B13)

### ISSUE THREAD

**Issue by samuelp-mw** [ivicos-GmbH/jitsi-meet#26]
## Description

Some users leaving the conference remain sometimes displayed in the discussion. The goal of this issue is to investigate the root cause of this.

## Acceptance criteria
* [ ] : PR opened to correct the issue or findings documented if cannot be fixed

**Comment by samuelp-mw** [comment]
Related issues are already mentioned here ;
* https://github.com/jitsi/jitsi-meet/issues/6338
* https://github.com/jitsi/jitsi-meet/issues/7304

Ghost users may exist on lost connection. In that case, the desired behavior is that the ghost user remains 60s (timeout) in the room. However, the ghost user should not remain more than this timeout. It should be confirmed whether a contrary behavior has been noticed?

Any accurate description of the behavior/bug may be useful in order to identify potential fixes.

**Comment by samuelp-mw** [comment]
* Browsing existing issues open source
* Looking whether timeout configurable or not (reduce it if possible)
* If issues, occur, will be easier to debug

**Comment by UlrichBoettger** [comment]
You can find the ghost of Holger in my room

**Comment by ivicos-friedrich** [comment]
<img width="617" alt="Bildschirmfoto 2021-04-14 um 11 36 55" src="https://user-images.githubusercontent.com/74658146/114692419-e3b50780-9d18-11eb-9b53-c4fdc218a897.png">

The ghost users are not marked as disconnected, but as connected, with good connectivity

**Comment by samuelp-mw** [comment]
@UlrichBoettger @ivicos-friedrich 
Thanks for the information. I will have to think about which element could help me to know what has happened and how to debug the issue. There is also a functionnality being developed in Jitsi enabling to kick-out a participant. That could be interesting to be able at least to have a workaround for this kind of bugs, right? Due to the difficulty to debug all the possible edge cases that can occur, maybe enabling this functionnality could be a safe start. What do you think @ivicos-friedrich ?

**Comment by UlrichBoettger** [comment]
yes it would be a workaround, but it would also be a great feature to "stongly ask someone to leave the room ;-)"

**Comment by samuelp-mw** [comment]
The functionnality existing now is :
* **kickParticipant** : command enabling to kick a Participant out of the meeting based on the participantId. It is possible to do it programmatically for now (only for the moderator) :
``` api.executeCommand('kickParticipant',participantId) ```
* An event is then sent to notify the user : `participantKickedOut`

**Comment by samuelp-mw** [comment]
The issue https://community.jitsi.org/t/solved-conference-leftover/17127/4 seems to indicate a way to set the timeout for participants on lost connection. `bosh_max_inactivity` could probably be configured in order to change the timeout setting. However, we should see whether a setting enables to do that from an external configuration.

**Comment by samuelp-mw** [comment]
An attempt to fix short ghost users issue is being handled in Ansible repository : https://github.com/ivicos-GmbH/ansible-jitsi-meet/issues/43

**Comment by samuelp-mw** [comment]
> yes it would be a workaround, but it would also be a great feature to "stongly ask someone to leave the room ;-)"

@UlrichBoettger Does the issue exist since more than a week?

**Comment by samuelp-mw** [comment]
> An attempt to fix short ghost users issue is being handled in Ansible repository : [ivicos-GmbH/ansible-jitsi-meet#43](https://github.com/ivicos-GmbH/ansible-jitsi-meet/issues/43)

This has been deployed to staging and the ghost user looks to be invisible after the specified timeout (5s for the test)

**Comment by samuelp-mw** [comment]
Some issues were known regarding ghost users with prosody version 0.10. However, it seems that it was fixed in version 0.11 currently deployed in production.

**Comment by krish0005** [comment]
We have this problem everywhere in all environments including Production and we use the following versions:

```
jitsi_meet_version: "1.0.4466"
jicofo_version: "1.0-644"
prosody_version: "0.11.8"
prosody_module_luasec: "0.6-4"
prosody_module_luarocks: "2.4.2"
prosody_module_liblua: "5.2.4"
prosody_module_liblua_dev: "5.2.4"
```

Is there any chance to have it fixed and if yes which version we need to increment when re-deploying JITSI ?

Thank you

**Comment by samuelp-mw** [comment]
Hi @krish0005, 
This repository is not the official open-source Jitsi Meet repository but a custom fork of Jitsi Meet. The official repository is situated there https://github.com/jitsi/jitsi-meet. I guess that opening an issue there would be the most efficient in order to get some feedbacks related to that issue.
In our case, ghost users happen really seldomly. The reason for that has not been identified yet.
