### ISSUE TITLE
Audio quality improvement

### ISSUE THREAD

**Issue by samuelp-mw** [ivicos-GmbH/jitsi-meet#38]
## Description

Implement a NoiseGate, to reduce the input gain when a participant is not speaking. 
Apply Lowpass and Highpass filters, and a bit of Compression before the NoiseGate to get the audio signal as clean as possible from the client-side.

## Acceptance criteria

- [x] Locate where are the WebAudio getUserMedia { audio: constraints } implemented. **[Located here](https://github.com/ivicos-GmbH/lib-jitsi-meet/blob/08ce96d881fed594d6f347cdb0a4076fdb050d28/modules/RTC/RTCUtils.js#L226)**
- [x] Implement updated getUserMedia { audio: constraints } if needed. **FOR NOW NOT NEED TO UPDATE THEM**
- [x] Evaluate which NoiseReduction option is better for us: getUserMedia { audio: noiseSuppression } or Jitsi's RnNoiser ? **BETTER gUM NOISESUPPRESSION, RNNOISER SEEMS TO BE USED JUST FOR THE VAD SCORE**
- [x] Check if it's possible to use the existing Rnnoise analyser, or it's more efficient to build a WebAudio Analyser Node. **IT SEEMS IS A GOOD IDEA TO USE IT**
- [x] Create a new feature to apply Lowpass and Highpass filters, Compression and NoiseGate, and an Analyser if needed. **THAT SHOULD BE IMPLEMENTED IN LIB-JITSI-MEET**
- [x] Calibrate the NoiseGate threshold with different background noise.

### Useful Links

[Audio Constraints explanation](https://w3c.github.io/mediacapture-main/#dom-mediatracksettings-echocancellation)
[2018 Update: Audio Constraints are updated](https://stackoverflow.com/questions/31306309/how-to-disable-web-audio-analyzer-filtering-high-frequencies)

**Comment by LancharroDav** [comment]
WebAudio getUserMedia located in [lib-jitsi-meet project RTCUtils.js](https://github.com/ivicos-GmbH/lib-jitsi-meet/blob/08ce96d881fed594d6f347cdb0a4076fdb050d28/modules/RTC/RTCUtils.js#L226)

**Comment by LancharroDav** [comment]
Rnnoiser is an external library that uses wasm [link here](https://github.com/jitsi/rnnoise-wasm) and sometimes it seems to fail (see screenshot "wasm streaming compile failed" error).
<img width="1791" alt="Screenshot 2021-04-13 at 23 07 11" src="https://user-images.githubusercontent.com/49806971/114691229-bcaa0600-9d17-11eb-869b-ebd4bdbbf3a8.png">

Make sense to not use it, due to instability?

**Comment by samuelp-mw** [comment]
> Rnnoiser is an external library that uses wasm [link here](https://github.com/jitsi/rnnoise-wasm) and sometimes it seems to fail (see screenshot "wasm streaming compile failed" error).
> <img alt="Screenshot 2021-04-13 at 23 07 11" width="1791" src="https://user-images.githubusercontent.com/49806971/114691229-bcaa0600-9d17-11eb-869b-ebd4bdbbf3a8.png">
> 
> Make sense to not use it, due to instability?

That is true that I didn t look at all the visible issues in the log yet. This is interesting. I would be curious to know whether this issue is still there in our current fork version

**Comment by samuelp-mw** [comment]
As discussed, in order to modify the audio options, we need to change the config.js file. When executing locally, we only simulate part of the work done by the central Jitsi server (the other mechanisms, including configs are hosted by a Jitsi BE). This is mentioned here : https://community.jitsi.org/t/changed-config-js-or-interface-config-js-not-work/17689/2

This explains why changing the config locally does not work : In order to make it work, we will need to modify the config on a BE that we have access to : This can either be our deployed Jitsi in the cloud or a docker instance (we have the possibility to deploy a whole docker stack of Jitsi Meet locally). We can discuss/try one approach or the other depending on the most convenient option for us to develop.

**Comment by LancharroDav** [comment]
**TO BE CONFIRMED** We can get the audio level (values between 0 and 1) by calling `import JitsiMeetJS from '../../../../base/lib-jitsi-meet/_';

const JitsiTrackEvents = JitsiMeetJS.events.track;
const audioLevel = JitsiTrackEvents.TRACK_AUDIO_LEVEL_CHANGED`

reference: [MicrophoneEntry.js](https://github.com/ivicos-GmbH/jitsi-meet/blob/master/react/features/settings/components/web/audio/MicrophoneEntry.js)

**Comment by LancharroDav** [comment]
> > Rnnoiser is an external library that uses wasm [link here](https://github.com/jitsi/rnnoise-wasm) and sometimes it seems to fail (see screenshot "wasm streaming compile failed" error).
> > <img alt="Screenshot 2021-04-13 at 23 07 11" width="1791" src="https://user-images.githubusercontent.com/49806971/114691229-bcaa0600-9d17-11eb-869b-ebd4bdbbf3a8.png">
> > Make sense to not use it, due to instability?
> 
> That is true that I didn t look at all the visible issues in the log yet. This is interesting. I would be curious to know whether this issue is still there in our current fork version

I've checked running Jitsi in local and there are no warnings related to 'wasm', 'AudioContext', or 'RnNoiser' :)

**Comment by LancharroDav** [comment]
**GET AUDIO LEVEL**
We can get the audio level (values between 0 and 1) by calling

`import JitsiMeetJS from '../../../../base/lib-jitsi-meet/_';`

`const JitsiTrackEvents = JitsiMeetJS.events.track;`
`const audioLevel = JitsiTrackEvents.TRACK_AUDIO_LEVEL_CHANGED`

reference: [MicrophoneEntry.js](https://github.com/ivicos-GmbH/jitsi-meet/blob/master/react/features/settings/components/web/audio/MicrophoneEntry.js)

**GET VAD VALUE**
This value (between 0 and 1) gives us a speech presence value, being 0 no voice detected and 1 voice detected. The good point on using it to trigger the Noise Gate is that it could recognize the voice even if it has low volume (i.e. whispers).

To do that, as discussed with @samuelp-mw, we can use the Rnnoise 'calculateAudioFrameVAD', following the same structure as it's done for the Rnnoise.

reference: [NoiseGate Processor](https://github.com/ivicos-GmbH/jitsi-meet/tree/feature/audio_quality_improvement/react/features/stream-effects/noisegate)

**Comment by LancharroDav** [comment]
The Audio signal goes through the RnnoiseProcessor until the LocalAudioTrack is muted and the TALK_WHILE_MUTED popup appears. At this point, the process stops and is reactivated once the LocalAudioTrack is unmuted.

For our purposes using the VAD Value generated in the RnnoiseProcessor, this workflow is not a problem. Just discards the option to mute the LocalAudioTrack when not talking. Keep looking for a spot where the gain reduction could be applied in the JitsiLocalTrack without affecting the input level used by the RnnoiseProcessor.

**Comment by LancharroDav** [comment]
Primitive NoiseGate implemented, getting the audioLevel from remote thumbnails and modifying their volumes attributes depending on the incoming audiLevel. [**SEE CHANGES**](https://github.com/ivicos-GmbH/jitsi-meet/commit/08bc6b8074760d3a79b86bbfddda541840fd3e74)

**NEXT STEPS**
Find the way to attach an attribute with our VAD score to the JitsiTrack we send to the other participants, in order to have a better and more accurate voice recognition for the noisegate threshold.

Create an attack and release parameters for the noisegate, to have a smoother open and close of the gate.

**Comment by LancharroDav** [comment]
Basic Noise Gate process implemented by getting the audioLevels from each JitsiRemoteAudioTrack and modifying their respective Volume from Thumbnails depending on the audioLevel.

CHANGES:
[Thumbnails.js](https://github.com/ivicos-GmbH/jitsi-meet/blob/c8755d907cc6d655be626211f4ccc4cd7d116144/react/features/filmstrip/components/web/Thumbnail.js#L808)
[noisegate/index.js](https://github.com/ivicos-GmbH/jitsi-meet/blob/c8755d907cc6d655be626211f4ccc4cd7d116144/react/features/stream-effects/noisegate/index.js#L1)
